name: Docker Image Build and Push to Docker Hub

on:
  workflow_dispatch:
  push:
    tags:
      - '**.*.*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Run
        run: echo "yep"