name: Build

on:
  workflow_dispatch:
  push:
    branches: [staging]
    tags:
      - '*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Run
        run: echo "yep"