name: Build

on:
  push:
    branches:    
      - staging
    # Sequence of patterns matched against refs/tags
    tags:        
      - '*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Run
        run: echo "yep"