name: Release

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag/Version name'
        required: true
        default: 'warning'
        type: string

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout branch
        uses: actions/checkout@v3

      - name: Update changelog and package version
        run: |
          sed -i '3 i \\n## [${{ inputs.tag }}](https://github.com/${{ GITHUB_REPOSITORY }}/releases/tag/${{ inputs.tag }})' CHANGELOG.md
          sed -i 's/"version": "*"/"version": "${{ inputs.tag }}"/g' package.json

      - name: Commit changes to chosen branch
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git stage .
          git commit -m "Release version ${{ inputs.tag }}"
          git push

      - name: Create tag
        run: |
          git tag ${{ inputs.tag }}
          git push origin ${{ inputs.tag }}